### ISSUE TITLE
Proposal: strict repository structure and context-aware syntax

### ISSUE THREAD

**Issue by romshark** [qbeon/service-modelling-language#12]
This is a SML repository structuring and syntax proposal meant to improve consistency, intuitivity and potential parsing performance.

This proposal is based on the [structuring-proposal branch](https://github.com/qbeon/service-modelling-language/tree/structuring-proposal).

### Rules
The following strict rules would be introduced:
- Each file houses only 1 type declaration, not more, not less.
- File names reflect the type they describe.
- Type categories are placed in special subdirectories:

| type category | directory |
|:-|:-|
| Entities | `./entity/` |
| Structures | `./struct/` |
| Enumerations | `./enumeration/` |
| Scalars | `./scalar/` |
| Errors | `./error/` |
| Transactions | `./transaction/` |
| Events | `./events/` |
| Unions | `./union/` |
| Relations | `./relation/` |
| User entities | `./user` |

- `./root.sml` always represents the graph root node
- `*.sml` files are not allowed to be placed in the project root directory `./`
- Syntax becomes context-aware and changes to:

```
<type> <serviceName> :: <typeName>

<context-aware-expressions>
```

- access permissions may be defined in a separate file following the obligatory naming convention: `<typeName>_access.sml`

### Disadvantages
- Some files will only be 2 lines in size, 100 different error types for example where each is just 2 lines is probably a smell.
- Impossible to group certain semantically connected types in 1 file.

### Advantages
- Consistency, all SML projects have the same structure making it easier to work on multiple projects at once and reading other people's schemas
- Performance, all files can be parsed in parallel improving parser performance because a file can only be parsed by one thread at a time.
- Context-aware syntax. Language syntax can be reduced and simplified by making it context aware where a file might describe only 1 thing. For example `access Type {}` becomes `access {}` because `access` becomes context-aware.
- No `*.sml` files in the project root allowing to keep it rather clear.
- Less choice means more productive developers:
  - no more "how do we name those files properly? what convention to choose?"
  - no more textual searching for a type (when there's no intellisense present), because you always know the file name the type is declared in.
  - conventions don't change over time
  - git log can be kept clear, removing a file = removing a type, adding one = adding a new type
- More parallel syntax error outputs, if some errors are behind others, they'll remain hidden until those are fixed. Having more files means having less "initially invisible" syntax errors.
- Improve intuitiveness since things like properties are declared in the `properties {}` block of the file, which would be too verbose for the old-style syntax
- 1 tab less indentation.
- Reduced cache misses, compiled code doesn't need to be recompiled again.

It should also be noted, that this syntax would probably make the parser implementation simpler (I might be wrong though)

**Comment by Xeizzen** [comment]
I think there is a necessity to ask users will they accept such restrictions, because they may be helpful and may bring positive results, but I fear some of the projects will be incompatible with such restrictions, so I think there is some necessity to ask a wide range of users in some kind of survey.

**Comment by romshark** [comment]
@Xeizzen I think we should start off with this structure in the alpha and then look at whether or not people actually like it and what problems it causes that are currently not apparent because the advantages clearly outweigh the disadvantages for now.

**Comment by romshark** [comment]
What's not clear yet is how to better reference properties and hidden properties (such as `:id`) in `access` declarations:

```
user ExampleService::User

properties {
  a Uint32
  b Uint32
}

access a {
  allow User as u {
    if u.a == User.a
    if u == User:id
  }
}
```
The above variant could be a little confusing when the user type and the accessed user entity type are the same as in the above example.

There's also another alternative:
```
user ExampleService::User

properties {
  a Uint32
  b Uint32
}

access a {
  allow User as u {
    if u.a == properties::a
    if u == properties:::id
  }
}
```
where `:::` references hidden properties.

referencing a just with `a` is not an option, since there might be a naming conflict with a builtin keyword and thus properties wouldn't be allowed to carry same names as those contextual keywords, which is bad (too restrictive).

**Comment by Xeizzen** [comment]
Triple colon seems so distracting and confusing so I would immediately disagree with such a feature.
And if we want to think about references to the object itself inside it we always can think what approach was made in other languages, such as C++ for example, with the keyword "this", and such as python, with the keyword "self".

So the above example could look like this:

```
user ExampleService::User

properties {
  a Uint32
  b Uint32
}

access a {
  allow User as u {
    if u.a == this.a
    if u == this:id
  }
}
```

**Comment by romshark** [comment]
@Xeizzen  yes, `this` actually makes sense, since we're executing this rule on concrete instances of `User` while `this` references it. `this` would therefor be a reserved contextual keyword.

**Comment by romshark** [comment]
One way to address the "1-line-files" and "global namespace pollution" problems (when, for example, a small function that's used only once in the entire schema needs to be declared as `function/ExampleFunction.sml`) is to make `entity`, `user`, `struct`, `transaction`, `event`, `relation` and `error` declarations become their own namespaces that can house less complex types:

- `entity` / `user` can house sub-declarations of:
  - `struct`
  - `scalar`
  - `enum`
  - `function`
  - `union`
- `struct` can house sub-declarations of:
  - `struct`
  - `scalar`
  - `enum`
  - `union`
  - `function`
- `transaction` can house sub-declarations of:
  - `struct`
  - `scalar`
  - `enum`
  - `error`
  - `union`
  - `function` (because they might be needed in structs)
- `error` can house sub-declarations of:
  - `struct`
  - `scalar`
  - `enum`
  - `union`
  - `function` (because they might be needed in structs)
- `event` can house sub-declarations of:
  - `struct`
  - `scalar`
  - `enum`
  - `union`
  - `function` (because they might be needed in structs)
- `relation` can house sub-declarations of:
  - `struct`
  - `scalar`
  - `enum`
  - `union`
  - `function` (because they might be needed in structs)

This has a few disadvantage:
- Some namespaces might be redeclaring types that could actually be reused, but this is rather a minor disadvantage.
- The declaration syntax would need to be reverted to the previous one to allow for declarations of multiple types in a single file (while still keeping the project sources structured according to this proposal)
- Code generating becomes a bit tricky, since any of the above types could be namespaces to multiple type declarations which would make generating Go code a bit tricky.
