### ISSUE TITLE
Proposal: plural project directory naming

### ISSUE THREAD

**Issue by Xeizzen** [qbeon/service-modelling-language#16]
The recently accepted proposal #12 suggested a strict project structure with specific folders for specific types, yet I propose changing the directory names to their plural versions:

- `entities` instead of `entity`
- `enums` instead of `enum`
- `errors` instead of `error`
- `events` instead of `event`
- `relations` instead of `relation`
- `scalars` instead of `scalar`
- `structs` instead of `struct`
- `transactions` instead of `transaction`
- `unions` instead of `union`
- `users` instead of `user`

Some may argue that this is merely a question of preference, but I doubt it. In my opinion, the names of containers should reflect what they contain - a singular name form suggests that they only contain one thing.

**Comment by romshark** [comment]
@Xeizzen as you already said, it's just a question of preference, though I agree with your argument, maybe we really should change it.
