### ISSUE TITLE
Proposal: source code sub-directory

### ISSUE THREAD

**Issue by Xeizzen** [qbeon/service-modelling-language#18]
The language now has an accepted strict project structure, as suggested in issue #12 .
But wouldn't it also make sense to put all source code in a "src" sub-directory?
```
project/
    README.md
    src/
        entities/...
        structs/...
        errors/...
        enumns/...
        scalars/...
        events/...
        relations/...
        transactions/...
        users/...
        unions/...
        root.sml
    .sml/...
    dependencies/
        gitlab.com/
            qbeon/
                package/...
        github.com/
            romshark/
                package/...
```

**Comment by romshark** [comment]
If we agree on #5 then I'm not sure where packages that are a direct part of the source code would go. Theoretically, they'd need to be in `/src/` then while third-party packages retrieved from remote git repositories would go to `/dependencies/<sourcepath>/`.

We might want to split the `/src/` sub-directory in package-directories then while `src/service/` would automatically be considered the service model schema package:

```
project/
   .sml/...
    README.md
    src/
        service/
            entities/...
            structs/...
            errors/...
            enumns/...
            scalars/...
            events/...
            relations/...
            transactions/...
            users/...
            unions/...
            root.sml
        pack1/
            entities/...
            structs/...
            errors/...
            enumns/...
            scalars/...
            events/...
            relations/...
            transactions/...
            users/...
            unions/...
            root.sml
    dependencies/
        gitlab.com/
            qbeon/
                package/...
        github.com/
            romshark/
                package/...
```

If a package doesn't have a `/src/service/` package directory then it's considered a "_library_". A library is a collection of packages that doesn't describe a service model schema.

**Comment by Xeizzen** [comment]
Yes, exactly. This slipped from my mind when I suggested the original proposal.
And yes, we could divide the project on multiple packages, but what if the project is too small to be separated in multiple packages, or there is no necessity in it? Would we allow to keep all the project-specific folders ("structs", "enums") within the "src" package, or we have to put everything in the "service" folder?
Also It made me curious of why you named the proposed "main" folder "service". Is it to follow the name of the language? Why not just name it "main", as you could expect from the main package?
But thinking about it, it made me curious, what if we mark the type of the project itself by naming it's central folder in certain way?
Like if there will be libraries, then the main folder will be named "lib" or "library", if it will be a service, then as you suggested it will be named "service".
What do you think?

**Comment by romshark** [comment]
@Xeizzen consistency-wise it's always better to have no extra rules, thus, if your model consists of only a single package it should still be `/src/service/`.

> Also It made me curious of why have you named the proposed "main" folder as "service". Is it to follow the name of the language? Why not just name it as "main", as you could expect from the main package?

Since SML is all about services - `service` is just rather intuitive. When your writing a library then `main` could become confusing, does a library automatically become a service model if there's a `main` package?

> Like if it will be a library, then the main folder will be named "lib" or "library", if it will be a service, then as you suggested it will be named as a "service".

A library is a collection of packages, it doesn't have a primary "main" packages, all packages of a library are treated equaly. Only services have a special `service` package since it's what the service model is generated from. A service package also always includes a `root.sml` file while regular packages don't.

**Comment by Xeizzen** [comment]
All of that make sense. I agree with this your arguments.
But I think we haven't talked about the dependencies clear enough.
What if our packages have a dependencies? Does it require for them to have their own "dependencies" folder inside them? If so, then what should we do if many packages will depend on the same thing? It will lead to multiple duplicates.
So to solve this problem, I suggest to give all packages an access to root "dependencies" folder.

And also, I believe it is hypothetically possible to have packages dependent on different versions of dependency. Have we got it covered? Could a dependency has a multiple versions of itself?
I mean, something like this:
```
dependencies
----dependency1
--------ver1.2
--------ver1.3
```

**Comment by romshark** [comment]
@Xeizzen 
> What if packages from src have dependencies? Does it require for them to have their own "dependencies" folder? If so, then what should we do if many packages will depend on the same thing? Won't It lead to multiple duplicates? To solve this problem, I suggest giving all packages access to the root `/dependencies` folder.

Packages that are part of the source-code of your project all use external dependencies from the shared `/dependencies` directory.

> And also, I believe it's hypothetically possible to have packages dependent on different versions of dependency. Have we got it covered? Could a dependency have multiple versions of itself?

I think I've covered this in #5 (or maybe not yet). Each and every project has a special hidden directory `.sml` in it, it stores the SML-repository which contains the entire version history of the project. Since the version history is immutably stored in every project you can easily import a certain version of an external dependency since it's just extracted from its repository.

**Comment by romshark** [comment]
Proposal accepted.
