### ISSUE TITLE
Proposal: page size limit

### ISSUE THREAD

**Issue by romshark** [qbeon/service-modelling-language#26]
This is a language feature proposal proposing the introduction of a new `access` attribute: `limit`, which is supposed to define the maximum queriable page size for a list property on a per-user-type basis:

```
access <listproperty> {
  [limit <usertype> [as $user] = <integer>|unlimited]
}
```

The `limit` attribute may only be applied to list properties:

```
root Example

properties {
  x []String
  y String
}

access x {
  allow User
  allow Admin

  // Constant page size limit
  limit User = 10

  // Dynamic page size limit
  limit Admin as $a = select {
    case ($a.isSuperAdmin) = unlimited
    default                = 100
  }
}

access y {
  allow Admin
  limit Admin = 2 // This is illegal, since y is not a list
}
```

The newly proposed built-in constant `unlimited` can be used as a value of the `limit` expression and lift the limit.

Limits of all lists are unlimited by default.

**Comment by Xeizzen** [comment]
Yes, this proposal can ease the load to the server, but I have a suggestion:
What if we instead of a keyword "unlimited" will use the integer? Like 0 or -1, which will mean the same thing?
I saw it being used multiple times, so it is quite common among the industry.

**Comment by romshark** [comment]
@Xeizzen `limit` should accept `Uint32` only I suppose and use `0` for unlimited then.

**Comment by romshark** [comment]
Since https://github.com/qbeon/service-modelling-language/commit/048ab37fb72fdcf15e9a40581f1885833808a66d `Array<T>` should no longer be slicable, `std::Slice<T>` should be used for slicable arrays instead. `access` blocks should probably be completely revamped, the `limit` statements in `access` blocks should be dropped, instead, the new syntax should be:
```
allow [<property> [as <variable 1>]] for (<user type> | anyone) [as <variable 2>] [if <Bool>]
```

```
root Example

use {
  "std" 1.0
}

properties {
  x Slice<String>
  y String
}

access {
  // Allow all User clients to access the graph root
  allow for User
  // Allow all Admin clients to access the graph root
  allow for Admin

  // Allow User clients to set x.$limit to a value that's <= 10
  allow x.$limit as $arg for User if $arg <= 10

  // Allow super admin clients to set unrestricted values for x.$limit,
  // all other admin clients should only be allowed to set it to max 100
  allow x.$limit as $arg for Admin as $a = select {
    case ($a.isSuperAdmin) = true
    default                = $arg <= 100
  }

  allow y for Admin
}
```

**Comment by romshark** [comment]
The page-size limit syntax proposal is rejected since this is now done by describing property parameter permissions.
