### ISSUE TITLE
Confusing syntax: optional relation declaration

### ISSUE THREAD

**Issue by romshark** [qbeon/service-modelling-language#7]
Currently, optional relations are declared this way:
```
entity T {
  unidirect -> ?T
  bidirect  <-> ?T.bidirect
}
```
Which is confusing because it reads like: "relation to an optional `T`" which is wrong because it's actually an _optional relation_ to a `T`.

An alternative syntax would be more consistent:
```
entity T {
  unidirect ? -> T
  bidirect  ? <-> T.bidirect
}
```

**Comment by Xeizzen** [comment]
The second option is definitely more plausible, but also there are alternative variants came to my mind, like using <~> for denoting optional relations. It opts for misreads, actually, because people will tend to confuse the tilde sign with regular dash sign.

**Comment by romshark** [comment]
@Xeizzen

![selection_001](https://user-images.githubusercontent.com/9574743/51186835-d3fcad80-18da-11e9-9f2f-22536020a85b.png)
- it'd looks rather confusing IMO
- it's easy to misread and very tiring for the eyes IMO
- it would harm consistency since regular types are still declared optional using `?`

I don't think this is a good idea.

**Comment by Xeizzen** [comment]
It's just an idea that came to my mind. I also think that this will confuse people.
But anyway - still an attempt to save the day and solve the problem.
Right now stick to the second option you declared in the head of this issue.

**Comment by romshark** [comment]
I think we can resolve this issue by changing the syntax to `? ->` because the former is inconsistent in regard to how other types are declared optional considering that relations are types too.
